name: ediris IOS NEW RELEASE
on:
  repository_dispatch:
    types: [ediris IOS New Release]
      
jobs:
  build-ios:
    runs-on: macOS-latest
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        ref: ${{ github.event.client_payload.branch || 'ediris-app-deployment' }}
        fetch-depth: 0

    - name: iOS Version Bump
      run: fastlane ios increment_version
    
    - name: Install dependencies
      run: npm ci

    - name: Install pods
      run: cd ios && pod install
           
    - name: Create IPA Build
      env:
          #FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }} 
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          #MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          CI_KEYCHAIN_NAME: ${{ secrets.CI_KEYCHAIN_NAME }}
          CI_KEYCHAIN_PASSWORD: ${{ secrets.CI_KEYCHAIN_PASSWORD }}
          DEVELOPER_TEAM_ID: ${{ secrets.DEVELOPER_TEAM_ID }}
          SIGNING_IDENTITY: "Apple Distribution"
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          LANG: en_GB.UTF-8
          LC_ALL: en_GB.UTF-8
      run: fastlane ios beta

    - name: Commit changes
      run: |
          git config --global user.name 'edirisdevops'
          git config --global user.email 'devops@ediris.test'
          git pull origin ediris-app-deployment
          git add -A
          git commit -m "Bump up iOS Release Version by CI"
          git push origin ediris-app-deployment      

  sendmail:  
    name: Send Mail 
    needs: build-ios 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:            
    - name : checkout
      uses: actions/checkout@master
    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1
      env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SCRIPT_FILEPATH: ./.github/google_settings/scripts/sendgrid_edirisios.js  