name: Precisely_IOS_CI

on:
  repository_dispatch:
    types: [Precisely IOS App]

      
jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 50
    #env: 
    #  DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_AUTH }}
        ref: ${{ github.event.client_payload.branch || 'precisely-spectrum-spatial-connect' }}
        fetch-depth: 0 

    - name: Install dependencies
      run: npm ci

    - name: Install pods
      run: cd ios && pod install
           
    - name: Create IPA Build
      env:
          #FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }} 
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          GIT_REPO_URL: ${{ secrets.PRECISELY_GIT_REPO_URL }}
          #MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          CI_KEYCHAIN_NAME: ${{ secrets.CI_KEYCHAIN_NAME }}
          CI_KEYCHAIN_PASSWORD: ${{ secrets.CI_KEYCHAIN_PASSWORD }}
          DEVELOPER_TEAM_ID: ${{ secrets.DEVELOPER_TEAM_ID }}
          SIGNING_IDENTITY: "Apple Distribution"
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          LANG: en_GB.UTF-8
          LC_ALL: en_GB.UTF-8
      run: fastlane ios beta

    - name: Commit changes
      run: |
          git config --global user.name 'buzzydevops'
          git config --global user.email 'devops@buzzy.buzz'
          git add -A
          git commit -m "iOS version bump by CI"
          git push --force 


  sendmail:  
    name: Send Mail 
    needs: build 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:            
    - name : checkout
      uses: actions/checkout@master
    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1
      env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SCRIPT_FILEPATH: ./.github/google_settings/scripts/sendgrid_preciselyios.js  

    #- name: Upload To TestFlight
     #  uses: actions/upload-artifact@v1
     # with:
     #     name: buzzy_rn.ipa
     #     path: "/Users/runner/work/buzzy_rn/buzzy_rn/fastlane/build/buzzy_rn.ipa" 
     # env:
     #   FASTLANE_USERNAME: ${{ secrets.APPLE_ID }}
     #   FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
     #   APPLE_ID: "954176500"
     # run: fastlane pilot upload -u $FASTLANE_USERNAME -p $APPLE_ID -i /Users/runner/work/buzzy_rn/buzzy_rn/fastlane/build/buzzy_rn.ipa --skip_waiting_for_build_processing true --verbose    


  