name: Precisely_Android_CI_V2
on:
  repository_dispatch:
    types: [Precisely Android App]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_AUTH }}
          ref: ${{ github.event.client_payload.branch || 'precisely-spectrum-spatial-connect' }}
          fetch-depth: 0

      - name: Decrypt keystore and Google Credential
        run: sh ./.github/google_settings/scripts/android-gpg-extract.sh
        env:
          ENCRYPT_PASSWORD: ${{ secrets.ENCRYPT_PASSWORD }}

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.2

      - shell: bash
        run: mkdir toolchains
      - name: specify NDK
        uses: ravinderjangra/android-ndk-toolchain-setup@0.2
        with:
          api: '21'
          arch: 'x86'
          install-location: 'toolchains'
          force: true    
      
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      
      - uses: actions/setup-node@v1
        with:
          node-version: '12.5'
      - name: Install Fastlane        
        run: bundle install
     
      - name: Install dependencies
        run: npm ci    

      - name: Run jetify
        run: npm run jetify
      
      - name: Increase watchers - add into the system config
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        
      - name: Dump secrets to .env
        run: env > .env
        env:
          REQUIRED_ENV: ${{ secrets.REQUIRED_ENV }}
      
      - name: Version bump
        #run: (cd ./android && bundle exec fastlane IncrementBuildNumber)        
        run: bundle exec fastlane android IncrementBuildNumber

      - name: Bundle and Upload to PlayStore
        #run: (cd ./android && bundle exec fastlane beta)        
        run: bundle exec fastlane android beta
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.PRECISELY_RELEASE_ALIAS}}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.PRECISELY_KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.PRECISELY_KEY_PASSWORD }}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Android version bump by CI"
          
  sendmail:  
      name: Send Mail 
      needs: build 
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps:            
      - name : checkout
        uses: actions/checkout@master
      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1
        env:
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            SCRIPT_FILEPATH: ./.github/google_settings/scripts/sendgrid_precisely_android.js  