name: PROTO_RELEASE_CI

on:
  repository_dispatch:
    types: [Proto App New Release]
      
jobs:
  
  update_iOS:    
    runs-on: macOS-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2       
      with:
        token: ${{ secrets.ACTIONS_AUTH }}
        ref: ${{ github.event.client_payload.branch || 'proto-app-deployment' }}       
           
    - name: iOS Version Bump
      run: fastlane ios increment_version

    - name: Commit and push changes
      run: |
          git config --global user.name 'buzzydevops'
          git config --global user.email 'devops@buzzy.buzz'
          git add -A
          git commit -m "Bump up iOS Release Version by CI"
          git push origin proto-app-deployment    
  
  build_ios:
    needs: update_iOS
    runs-on: macOS-latest
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_AUTH }}
        ref: ${{ github.event.client_payload.branch || 'proto-app-deployment' }}
        fetch-depth: 0

    - name: Install dependencies
      run: npm ci

    - name: Install pods
      run: cd ios && pod install
           
    - name: Create IPA Build
      env:
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }} 
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          GIT_REPO_URL: ${{ secrets.PROTO_MATCH_URL }}
          #MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          CI_KEYCHAIN_NAME: ${{ secrets.CI_KEYCHAIN_NAME }}
          CI_KEYCHAIN_PASSWORD: ${{ secrets.CI_KEYCHAIN_PASSWORD }}
          DEVELOPER_TEAM_ID: ${{ secrets.DEVELOPER_TEAM_ID }}
          SIGNING_IDENTITY: "Apple Distribution"
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          LANG: en_GB.UTF-8
          LC_ALL: en_GB.UTF-8
      run: fastlane ios beta

    - name: Commit changes
      run: |
          git config --global user.name 'buzzydevops'
          git config --global user.email 'devops@buzzy.buzz'
          git pull origin proto-app-deployment
          git add -A
          git commit -m "Bump up iOS build number by CI"
          git push origin proto-app-deployment    
  

  ios_sendmail:  
    name: Send Mail 
    needs: [build_ios, update_iOS] 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:            
    - name : checkout
      uses: actions/checkout@master
    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1
      env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SCRIPT_FILEPATH: ./.github/google_settings/scripts/sendgrid_proto_ios.js    
  
  
  update_android:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2    
      with:
        token: ${{ secrets.ACTIONS_AUTH }}
        ref: ${{ github.event.client_payload.branch || 'proto-app-deployment' }}       
        fetch-depth: 0

    - uses: actions/setup-ruby@v1
      with:
          ruby-version: '2.x'

    - name: Install Bundle
      run: bundle install  

    - name: Android Version Name Bump
      run: bundle exec fastlane android increment_release_name           
   
    - name: Commit and push changes
      run: |
          git config --global user.name 'buzzydevops'
          git config --global user.email 'devops@buzzy.buzz'
          git pull origin proto-app-deployment   
          git add -A
          git commit -m "Bump up Android Release Version by CI"
          git push origin proto-app-deployment    


  build_android:
    needs: update_android
    runs-on: ubuntu-latest
    timeout-minutes: 50
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_AUTH }}
          ref: ${{ github.event.client_payload.branch || 'proto-app-deployment' }}
          fetch-depth: 0

      - name: Decrypt keystore and Google Credential
        run: sh ./.github/google_settings/scripts/android-gpg-extract.sh
        env:
          ENCRYPT_PASSWORD: ${{ secrets.ENCRYPT_PASSWORD }}

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.2
      
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      
      - uses: actions/setup-node@v1
        with:
          node-version: '12.5'
      - name: Install Fastlane
        #run: (cd ./android && bundle install)
        run: bundle install
     
      - name: Install dependencies
        run: npm ci    

      - name: Run jetify
        run: npm run jetify
      
      - name: Increase watchers - add into the system config
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        
      - name: Dump secrets to .env
        run: env > .env
        env:
          REQUIRED_ENV: ${{ secrets.REQUIRED_ENV }}
      
      - name: Version Code Bump         
        run: bundle exec fastlane android IncrementBuildNumber

      - name: Bundle and Upload to PlayStore    
        run: bundle exec fastlane android beta
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.PROTO_KEY_ALIAS}}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.PROTO_KEYSTORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.PROTO_KEY_PASSWORD }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'buzzydevops'
          git config --global user.email 'devops@buzzy.buzz'
          git pull origin proto-app-deployment 
          git add -A
          git commit -m "Bump up Android Build Number by CI"
          git push origin proto-app-deployment    


  android_sendmail:  
    name: Send Mail 
    needs: [build_android, update_android] 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:            
    - name : checkout
      uses: actions/checkout@master
    - name: SendGrid
      uses: peter-evans/sendgrid-action@v1
      env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SCRIPT_FILEPATH: ./.github/google_settings/scripts/sendgrid_android_proto.js  

  